### PR TITLE
Fixes #42: Index out of bound on sending incomplete request method

### LINKED ISSUE #42: Index out of bound on sending incomplete request method
```
nim c -r tests/helloworld.nim
printf "G" | nc localhost 8080
```

Fails with
```
Listening on port 8080
/home/grfork/reps/httpbeast/src/httpbeast.nim(296) eventLoop
/home/grfork/reps/httpbeast/src/httpbeast.nim(203) processEvents
/home/grfork/reps/httpbeast/src/httpbeast.nim(115) slowHeadersCheck
/home/grfork/reps/httpbeast/src/httpbeast/parser.nim(10) parseHttpMethod
/home/grfork/.choosenim/toolchains/nim-1.4.0/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index 1 not in 0 .. 0 [IndexDefect]
Error: execution of an external program failed: '/home/grfork/reps/httpbeast/tests/helloworld '
```

### PR DESCRIPTION
**Pull request by Bahm**
Fixes #42. That's all I checked – I don't know if it's a good solution or what impact it has on performance.

### CODE REVIEW

File: src/httpbeast/parser.nim [hunk 1]
```diff
@@ -7,26 +7,33 @@ proc parseHttpMethod*(data: string, start: int): Option[HttpMethod] =
...
+    if data.high >= start+5 and
+       data[start+1] == 'E' and data[start+2] == 'L' and
        data[start+3] == 'E' and data[start+4] == 'T' and
        data[start+5] == 'E':
       return some(HttpDelete)
   of 'O':
-    if data[start+1] == 'P' and data[start+2] == 'T' and
+    if data.high >= start+6 and
+       data[start+1] == 'P' and data[start+2] == 'T' and
        data[start+3] == 'I' and data[start+4] == 'O' and
```
Comment (dom96) [inline src/httpbeast/parser.nim:37]: We shouldn't need this, at this point I think it's safe to assume the request is valid (since this only gets called in http request callbacks).

**Review by dom96 — CHANGES_REQUESTED** [review]
Thanks for the fix, please see comment and then it's ready for merge

File: src/httpbeast/parser.nim (hunk 1 above)
Comment (Bahm) [reply src/httpbeast/parser.nim]: I've just confirmed that, without these changes, `printf "G" | nc localhost 8080` causes the server to crash, which was the original example in #42. The changes to httpbeast.nim only fix `echo "" | nc localhost 8080`.
